phonebook = {"Alice":"123","hl":"234"};
print phonebook["Alice"];
d = dict(name="hl",age=29);
print d["name"];
print len(d);
d["gender"] = 'male';
print d["gender"] ;
del d["gender"];
print d;
print "name" in d;
